alias gitrh='git reset HEAD --hard'
alias gitr='git reset HEAD'
alias gitrs='git reset HEAD\^ --soft'
alias push="git push --tags"
alias pull="git pull"
alias pp="pull && push"
alias st="git status"
alias stash_pull_pop="git stash && git pull && git stash pop"
alias gc="git commit -v"
alias gd='git diff'
alias gs='git status'
alias gl='git log'
alias gsl='git shortlog origin/master..HEAD'
alias gitg='git log --oneline --decorate --graph'
alias gitf='git flow'
alias gdeploy='git push production master && terminal-notifier-notify -title "Deploy" -message "Deploy complete"'
alias gstage='git push staging $(current_branch):master'
alias gpr='git pull --rebase origin $(current_branch)'
alias gcob='git checkout -b'
alias gch='copy_and_echo `git rev-parse HEAD | tr -d "\n"`'
alias gcb='copy_and_echo $(current_branch)'
alias gcobr='copy_and_echo "origin/$(current_branch)"'
alias gh='gch'
alias gr='git rebase'
alias gbi='git bisect'
alias git-rebase-with-master='git fetch -p && git rebase origin/master'
alias update-branch='git fetch && git merge origin/master'
alias gfixup='git add . && git commit -a --amend --no-edit'
alias gamend='git commit --amend --no-edit'
